### ISSUE TITLE
Issue with doc comment code samples

### ISSUE THREAD

**Issue by EdenEast** [arzg/vim-rust-syntax-ext#5]
The official rust syntax plugin [rust-lang/rust.vim][rust-lang] correctly highlights code blocks in doc comments. When adding the rust-syntax-ext it overrides this function and removed syntax highlight for doc code blocks.

They accomplish this by defining a [rustCommentDocCodeFence][fence] that disables formatting
in the code block.

To resolve this issue either do not override this as `rsDocComment` or implement a similar feature.

Default rust-lang/rust.vim:

![rust-vim](https://user-images.githubusercontent.com/2746374/81590554-f694be80-9388-11ea-83c3-980e4fc5af8b.png)

rust-syntax-ext:

![extension](https://user-images.githubusercontent.com/2746374/81590597-09a78e80-9389-11ea-8d49-15dd490ad753.png)

[rust-lang]: https://github.com/rust-lang/rust.vim
[fence]: https://github.com/rust-lang/rust.vim/blob/6d5f3d8/syntax/rust.vim#L244,L269

**Comment by arzg** [comment]
Sorry, for the late reply, I’ve been busy with other projects.

This is definitely something I would like to implement – I would prefer adding our own solution instead of relying on rust.vim being installed (whether installed by the user or shipped with Vim).

**Comment by lunacookies** [comment]
Sorry, for the late reply, I’ve been busy with other projects.

This is definitely a good idea to implement – I would prefer adding our own solution instead of relying on rust.vim being installed (whether installed by the user or shipped with Vim).

I’ve created a pull request that implements doctest support (#7); can you test it out to see if it fulfils your needs?

**Comment by EdenEast** [comment]
Tested PR #7 and this pr fixed the issue I was having. Thanks!

**Comment by lunacookies** [comment]
Glad it works :)
